# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#d7ffcd"  # Accent color for interactive elements
backgroundColor="#333333"  # Main background color
secondaryBackgroundColor="#444444"  # Sidebar or secondary background color
textColor="#FFFFFF"  # Text color to ensure readability on a dark background
font="sans serif"  # Font type
